spring.datasource.url=jdbc:postgresql://dpg-cjj8b07jbvhs73fm27ag-a.oregon-postgres.render.com:5432/portfoliocontact
spring.datasource.username=root
spring.datasource.password=z0znSoSZm3qUg8R5HRNdZSxFRbmmwCrT

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

